name: toogoodtogo-ha-mqtt-bridge

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '17 3 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:

  toogoodtogo-ha-mqtt-bridge:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: toogoodtogo-ha-mqtt-bridge/
          file: toogoodtogo-ha-mqtt-bridge/Dockerfile-real
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: |
            maxwinterstein/homeassistant-addon-toogoodtogo-ha-mqtt-bridge:latest
